# ===== BASE =====
set -g mouse on
set -g history-limit 10000
set -g base-index 1
setw -g pane-base-index 1

# ===== ESTILO VISUAL (GUI FEEL) =====
set -g status on
set -g status-position bottom
set -g status-style bg="#1e1e2e",fg="#cdd6f4"

set -g window-status-current-style bg="#89b4fa",fg="#1e1e2e,bold"
set -g window-status-style bg="#313244",fg="#a6adc8"

set -g status-left "#[bg=#89b4fa,fg=#1e1e2e,bold]   TMUX #[default]"
set -g status-right "#[fg=#a6adc8]%d/%m %H:%M"

# ===== JANELAS / PAINEL ESTILO DESKTOP =====
#setw -g window-style bg="#11111b"
#setw -g window-active-style bg="#181825"

# divisões mais visuais
set -g pane-border-style fg="#313244"
set -g pane-active-border-style fg="#89b4fa"

# prefix mais confortável
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# splits estilo “tiling WM”
bind | split-window -h
bind - split-window -v

# reload config
bind r source-file ~/.tmux.conf \; display-message "reload OK"

# TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
