# Apps em ~/.config/
CONFIG_APPS=(
  nvim
  hypr
  kitty
  waybar
  btop
  fastfetch
  gtk-3.0
  gtk-4.0
  qt5ct
  qt6ct
  swaync
  walker
  wlogout
  yazi
  openbox
  cairo-dock
  eww
  hyprlock
  ascii
  fuzzel
  rofi
)

# Arquivos em $HOME/
HOME_FILES=(
  .zshrc
  .bashrc
  .profile
  .tmux.conf
)

# Arquivos de sistema (/etc) — formato: "origem=destino_relativo"
ETC_FILES=(
  /etc/ly/config.ini=etc/ly.conf
)
