# Monitor setup: apenas HDMI (desliga LVDS interno)
monitor = LVDS-1, disable
monitor = HDMI-A-1, preferred, auto, 1

exec-once = waybar

# Terminal (Kitty)
bind = SUPER, RETURN, exec, kitty

# Launcher
bind = SUPER, W, exec, wofi --show drun
# Fechar janela
bind = SUPER, Q, killactive

# Sair do Hyprland
bind = SUPER SHIFT, E, exit

# Fullscreen
bind = SUPER, F, fullscreen

# Foco (vim)
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

# Mover janelas
bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, L, movewindow, r
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, J, movewindow, d

# Workspaces
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3

# Reload config
bind = SUPER SHIFT, R, reload
